// ##### extgen :: Auto-generated file do not edit!! #####

#pragma once
#include "core/GMExtUtils.h"

// Internal function used for queueing buffers to native code
GMEXPORT double __EXT_NATIVE__ID3D11_queue_buffer(char* __arg_buffer, double __arg_buffer_length);

GMEXPORT double __EXT_NATIVE__id3d11_get_version(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_is_initialized();
GMEXPORT double __EXT_NATIVE__id3d11_shutdown();
GMEXPORT double __EXT_NATIVE__id3d11_get_last_hresult();
GMEXPORT double __EXT_NATIVE__id3d11_get_device_handle(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_get_context_handle(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_get_swapchain_handle(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_handle_query_interface(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_handle_is_valid(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_handle_get_kind(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_handle_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_get_feature_level(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_get_creation_flags(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_get_removed_reason(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_get_exception_mode(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_set_exception_mode(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_get_immediate_context(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_check_format_support(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_check_multisample_quality_levels(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_get_counter_info(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_create_buffer(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_create_buffer_with_data(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_buffer_get_desc(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_child_get_device(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_child_set_debug_name(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__id3d11_device_child_get_debug_name(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_child_set_private_data(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_child_get_private_data(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_resource_get_dimension(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_resource_get_eviction_priority(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_resource_set_eviction_priority(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_create_texture1d(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_create_texture1d_with_data(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_create_texture2d(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_create_texture2d_with_data(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_create_texture3d(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_create_texture3d_with_data(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_texture1d_get_desc(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_texture2d_get_desc(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_texture3d_get_desc(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_create_shader_resource_view_default(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_create_shader_resource_view(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_create_render_target_view_default(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_create_render_target_view(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_create_depth_stencil_view_default(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_create_depth_stencil_view(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_create_unordered_access_view_default(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_create_unordered_access_view(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_view_get_resource(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_shader_resource_view_get_desc(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_render_target_view_get_desc(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_depth_stencil_view_get_desc(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_unordered_access_view_get_desc(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_compile_shader(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_create_vertex_shader(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_create_hull_shader(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_create_domain_shader(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_create_geometry_shader(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_create_pixel_shader(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_create_compute_shader(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_create_geometry_shader_with_stream_output(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_create_input_layout(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_create_class_linkage(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_create_sampler_state(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_sampler_state_get_desc(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_create_rasterizer_state(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_rasterizer_state_get_desc(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_create_blend_state(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_blend_state_get_desc(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_create_depth_stencil_state(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_depth_stencil_state_get_desc(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_create_query(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_create_predicate(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_create_counter(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_create_deferred_context(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_finish_command_list(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_execute_command_list(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_get_type(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_get_context_flags(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_command_list_get_context_flags(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_asynchronous_get_data_size(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_query_get_desc(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_counter_get_desc(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_check_counter(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_begin(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_end(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_get_data(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_flush(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_clear_state(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_draw_indexed(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_draw(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_draw_indexed_instanced(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_draw_instanced(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_draw_auto(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_draw_indexed_instanced_indirect(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_draw_instanced_indirect(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_dispatch(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_dispatch_indirect(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_copy_subresource_region(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_copy_resource(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_update_subresource(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_map_read_to_buffer(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_map_write_from_buffer(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_copy_structure_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_clear_render_target_view(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_clear_unordered_access_view_uint(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_clear_unordered_access_view_float(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_clear_depth_stencil_view(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_generate_mips(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_set_resource_min_lod(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_get_resource_min_lod(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_resolve_subresource(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_ia_set_input_layout(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_ia_get_input_layout(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_ia_set_primitive_topology(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_ia_get_primitive_topology(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_rs_set_state(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_rs_get_state(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_om_set_blend_state(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_om_get_blend_state(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_om_set_depth_stencil_state(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_om_get_depth_stencil_state(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_om_set_render_targets(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_om_get_render_targets(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_om_set_render_targets_and_unordered_access_views(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_om_get_render_targets_and_unordered_access_views(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_so_set_targets(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_so_get_targets(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_cs_set_unordered_access_views(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_cs_get_unordered_access_views(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_set_predication(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_get_predication(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_ia_set_vertex_buffers(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_ia_get_vertex_buffers(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_ia_set_index_buffer(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_ia_get_index_buffer(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_rs_set_viewports(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_rs_get_viewports(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_rs_set_scissor_rects(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_rs_get_scissor_rects(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_vs_set_constant_buffers(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_vs_get_constant_buffers(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_vs_set_shader_resources(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_vs_get_shader_resources(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_vs_set_samplers(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_vs_get_samplers(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_hs_set_constant_buffers(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_hs_get_constant_buffers(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_hs_set_shader_resources(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_hs_get_shader_resources(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_hs_set_samplers(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_hs_get_samplers(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_ds_set_constant_buffers(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_ds_get_constant_buffers(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_ds_set_shader_resources(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_ds_get_shader_resources(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_ds_set_samplers(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_ds_get_samplers(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_gs_set_constant_buffers(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_gs_get_constant_buffers(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_gs_set_shader_resources(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_gs_get_shader_resources(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_gs_set_samplers(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_gs_get_samplers(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_ps_set_constant_buffers(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_ps_get_constant_buffers(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_ps_set_shader_resources(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_ps_get_shader_resources(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_ps_set_samplers(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_ps_get_samplers(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_cs_set_constant_buffers(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_cs_get_constant_buffers(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_cs_set_shader_resources(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_cs_get_shader_resources(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_cs_set_samplers(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_cs_get_samplers(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_vs_set_shader(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_vs_get_shader(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_hs_set_shader(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_hs_get_shader(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_ds_set_shader(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_ds_get_shader(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_gs_set_shader(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_gs_get_shader(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_ps_set_shader(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_ps_get_shader(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_cs_set_shader(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_device_context_cs_get_shader(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_class_linkage_get_class_instance(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_class_linkage_create_class_instance(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_class_instance_get_class_linkage(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__id3d11_class_instance_get_desc(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__id3d11_class_instance_get_instance_name(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__id3d11_class_instance_get_type_name(char* __arg_buffer, double __arg_buffer_length);

